### ISSUE TITLE
hello,a few questions.

### ISSUE THREAD

**Issue by tangyudi** [anson0910/CNN_face_detection#1]
Itś really nice of you to share your code,but i do not know where to start at first.Can you show me how to learn your code or to read which folder first?

**Comment by anson0910** [comment]
Hi, you can start from the file face_cascade_fullconv_fddb_single_crop.py

This file uses the CNN Cascade to write detection results on FDDB dataset to a file, so that it can be evaluated, it can also be easily modified to detect one single image and show detected rectangles.

**Comment by anson0910** [comment]
Hi, for testing, you can start from the file face_detection/face_cascade_fullconv_fddb_single_crop.py

This file uses the CNN Cascade to write detection results on FDDB dataset to a file, so that it can be evaluated, it can also be easily modified to detect one single image and show detected rectangles.

**Comment by tangyudi** [comment]
Thanks,and if I want to train these CNN net one by one where should i start?

**Comment by anson0910** [comment]
If you're not familiar with caffe's flow yet, dennis-chen's reply [here](https://github.com/BVLC/caffe/issues/550) gives a great picture.

### In order to train CNN Cascade: 
1. You should first download all faces from the AFLW dataset, and at least 3000 images without any faces (negative images).
2. Create negative patches by running **face_preprocess_10kUS/create_negative.py** with data_base_dir modified to the folder containing the negative images.
3. Create positive patches by running **face_preprocess_10kUS/aflw.py**
4. Run **face_preprocess_10kUS/shuffle_write_positives.py** and **face_preprocess_10kUS/shuffle_write_negatives.py** to shuffle and write position and labels of images to file.
5. Run **face_preprocess_10kUS/write_train_val.py** to create train.txt, val.txt and move images to corresponding folders as caffe requires.
6. Use scripts in **CNN_face_detection_models/create_lmdb_scripts/** to create lmdb files as caffe requires.
7. Start training by using such commands in terminal. <br>
`./build/tools/caffe train --solver=models/face_12c/solver.prototxt`

24 net and 48 net can be created in a similar way, however negative images shoud be created by running **face_preprocess_10kUS/create_negative_24c.py** and **face_preprocess_10kUS/create_negative_48c.py**

Calibration nets are also trained similarly, scripts can be found in **face_calibration/**


Hope that helps!

**Comment by tangyudi** [comment]
Thank you !I'm new in face detection.Your code help me a lot!

**Comment by anson0910** [comment]
No problem, glad to help!
