### ISSUE TITLE
ROC report on supplied models

### ISSUE THREAD

**Issue by facenx** [anson0910/CNN_face_detection#20]
Hello, Anson.

First of all thank you for sharing your code. It was very helpful to me.

I ran benchmark on FDDB and got not very impressive results:
![image](https://cloud.githubusercontent.com/assets/15029183/16944504/99fcadc8-4da9-11e6-8e41-d945a2af8bb0.png)
Does it mean that supplied models are only for demo and one should train its from scratch? Can I hope to obtain results similar to #18 in such way?

Thanks in advance.

**Comment by anson0910** [comment]
Hi,
I remember my results were better than this...

I think the results are not very impressive because of mainly 2 reasons:

1. To obtain the results on FDDB as in the paper, the author mentioned that he actually used a scaling factor of 1.18 instead of 1.414. To change the scaling factor, you can pass it in as an argument into the **detect_faces** or **detect_face_12c**  function.
2. The calibration nets were trained improperly before, so retraining the whole net would indeed achieve better results.

**Comment by facenx** [comment]
Hi,
Thanks for quick answer.

I got your points. But I am more interesting in content of _CNN_face_detection_/_CNN_face_detection_models_ repository on Jul 14 15:16:38 2016.

There are several random FDDB example:
![FDDB/2002/07/19/big/img_130.jpg](https://cloud.githubusercontent.com/assets/15029183/16994946/61a964de-4eb2-11e6-8986-97864047c03e.png)
![/home/uldin/datasets/FDDB/2002/07/19/big/img_135.jpg](https://cloud.githubusercontent.com/assets/15029183/16994972/807c2806-4eb2-11e6-98f0-d12e83047c39.png)
![/home/uldin/datasets/FDDB/2002/07/19/big/img_141.jpg](https://cloud.githubusercontent.com/assets/15029183/16995010/9c07c300-4eb2-11e6-959c-619c8b228d02.png)
![/home/uldin/datasets/FDDB/2002/07/19/big/img_158.jpg](https://cloud.githubusercontent.com/assets/15029183/16995020/af34c95a-4eb2-11e6-9012-9486f8d915d0.png)

What I actually did I cloned repositories and ran face_cascade_fullconv_single_crop_single_image.py script as noticed in readme.
Can you see something wrong on attached screenshots? Or it's like usual detector behavior.
My problem is that I really don't know how does it should work.

Thanks in advance.
