### ISSUE TITLE
About the quantizeBitNum and stochasticRoundedParams

### ISSUE THREAD

**Issue by tangyudi** [anson0910/CNN_face_detection#5]
You have help me so much,if you come to shanghai, remember to call me I will treat you dinner.
1.In your code,I see these two things(I do not know how to call them),what are they used to do ? Is there any difference?
2.what are the difference between the following choose?
if loadNet:
        net_12_cal = caffe.Net(MODEL_FILE, PRETRAINED, caffe.TEST)
    else:
        net_12_cal = caffe.Classifier(MODEL_FILE, PRETRAINED,
                           mean=np.load(caffe_root + 'python/caffe/imagenet/ilsvrc_2012_mean.npy').mean(1).mean(1),
                           channel_swap=(2,1,0),
                           raw_scale=255,
                           image_dims=(15, 15))

**Comment by anson0910** [comment]
Haha,  it's a pleasure to help!

1. Those 2 parameters are probably only useful to myself, because I'm hoping to implement the CNN cascade on hardware (more particularly, on an FPGA board), and since floating points are very expensive on hardware, I'll have to round them down to fixed-point representation, and there are several ways to do so...
If you need me to explain more, feel free to ask!

2. The reason why I used _Net_ later rather than _Classifier_ is also related to hardware issues..
Since I need to round the parameters and write them back to the model, and as far as I know, only _Net_  provides a way to make changes to the net. I also recall that one of the caffe authors recommend using _Net_ as well.

**Comment by tangyudi** [comment]
1.Have you implemented some other paper? I am new in face detection , your code really help me a lot.
2.If i want to deploy the code to server,when the user uploading a picture the code will load the caffe model , do you have some idea about just load the model one time on the server to continue provide the detection serve?

**Comment by anson0910** [comment]
Nope, I haven't implemented other papers so far, and probably won't do so in the near future, haha!

The model does only need to be loaded once, you can see the file **face_detection/face_cascade_fullconv_quantize_fddb.py**, it runs the CNN cascade on more than 5000 images.

**Comment by tangyudi** [comment]
I am interest in deep learning, but i do not have some resource about DL or caffe, can you share me some resource you have ever read?Do you have QQ or wechat? Can I add you?

**Comment by anson0910** [comment]
I started from [this](http://cs231n.github.io/) Stanford course website, I think it's really well written!

Sorry, I don't have QQ or wechat, I use Facebook and Line...
